# 创建者：v2rayse.com 自动创建
# 创建时间：2025-08-08 08:00:00
# 节点类型：ss, vmess, ssr
---
mixed-port: 7890
allow-lan: false
mode: "rule"
log-level: "info"
external-controller: "127.0.0.1:9999"
dns:
  enable: true
  listen: "0.0.0.0:53"
  ipv6: false
  default-nameserver:
  - "223.5.5.5"
  - "114.114.114.114"
  nameserver:
  - "223.5.5.5"
  - "114.114.114.114"
  - "119.29.29.29"
  - "180.76.76.76"
  enhanced-mode: "fake-ip"
  fake-ip-range: "198.18.0.1/16"
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - "router.asus.com"
  - "localhost.sec.qq.com"
  - "localhost.ptlogin2.qq.com"
  - "+.msftconnecttest.com"
tun:
  enable: true
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - "114.114.114.114"
  - "180.76.76.76"
  - "119.29.29.29"
  - "223.5.5.5"
  - "8.8.8.8"
  - "8.8.4.4"
  - "1.1.1.1"
  - "1.0.0.1"
proxies:
- name: "🇳🇱_NL_荷兰"
  type: "ss"
  server: "193.29.139.138"
  port: 8080
  cipher: "chacha20-ietf-poly1305"
  password: "QCXDxuDlTTMD7jtgHUjIoj"
- name: "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  type: "vmess"
  server: "142.171.224.111"
  port: 20086
  uuid: "0908eadd-7337-49dd-8e9b-e325bca02910"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  type: "ss"
  server: "156.146.40.194"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "🇷🇺_RU_俄罗斯"
  type: "ss"
  server: "77.105.166.12"
  port: 8594
  cipher: "chacha20-ietf-poly1305"
  password: "mSQiuT5jR17nyWgcXOPrTW"
- name: "🇺🇸_US_美国"
  type: "vmess"
  server: "3.149.233.188"
  port: 20086
  uuid: "158ee47c-c5f6-4892-8662-8fc113fb3d6b"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇮🇳_IN_印度->🇫🇷_FR_法国"
  type: "ss"
  server: "202.78.160.88"
  port: 8443
  cipher: "chacha20-ietf-poly1305"
  password: "c0iCgBG1Jma4QGutmZC17k"
- name: "🇺🇸_US_美国_1"
  type: "vmess"
  server: "38.106.3.14"
  port: 20086
  uuid: "766c0871-1359-4ae9-8921-0f468ec02722"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇺🇸_US_美国_2"
  type: "vmess"
  server: "64.81.30.24"
  port: 20086
  uuid: "f53e0d42-afca-4b76-ae7f-806d6a1d36c2"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇩🇪_DE_德国"
  type: "ss"
  server: "193.108.119.230"
  port: 8080
  cipher: "rc4-md5"
  password: "14fFPrbezE3HDZzsMOr6"
- name: "🇺🇸_US_美国_3"
  type: "vmess"
  server: "15.204.234.200"
  port: 41100
  uuid: "c7f169a3-2e9a-4894-ba53-7b2fa6fd08b4"
  cipher: "auto"
  network: "tcp"
  alterId: 0
- name: "🇩🇪_DE_德国_1"
  type: "ss"
  server: "45.87.175.166"
  port: 8080
  cipher: "chacha20-ietf-poly1305"
  password: "cvII85TrW6n0OGyfpHVS1u"
- name: "🇬🇧_GB_英国"
  type: "ssr"
  server: "62.100.205.48"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
  obfs: "plain"
  protocol: "origin"
- name: "🇺🇸_US_美国_4"
  type: "vmess"
  server: "23.184.200.69"
  port: 20086
  uuid: "ed715e84-81a0-40c5-bb6a-4d8d341e5cfa"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇺🇸_US_美国_5"
  type: "vmess"
  server: "050910.xyz"
  port: 20086
  uuid: "7e992138-4bae-44d7-893e-c33605c40d5f"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
    headers:
      host: "050910.xyz"
  alterId: 0
- name: "🇩🇪_DE_德国_2"
  type: "ss"
  server: "45.87.175.199"
  port: 8080
  cipher: "chacha20-ietf-poly1305"
  password: "cvII85TrW6n0OGyfpHVS1u"
- name: "🇺🇸_US_美国_6"
  type: "vmess"
  server: "64.81.30.225"
  port: 20086
  uuid: "7f499074-3408-4840-b55b-91142735d2cc"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇨🇳_CN_中国->🇺🇸_US_美国"
  type: "ss"
  server: "awes35lesl.blhao0o.dpdns.org"
  port: 12017
  cipher: "aes-128-gcm"
  password: "01721e43-5389-4f97-b21c-900abb2bda9e"
- name: "🇺🇸_US_美国_8"
  type: "vmess"
  server: "198.2.218.216"
  port: 44883
  uuid: "418048af-a293-4b99-9b0c-98ca3580dd24"
  cipher: "auto"
  network: "tcp"
  alterId: 64
- name: "🇺🇦_UA_乌克兰"
  type: "ss"
  server: "switcher-nick-croquet.freesocks.work"
  port: 443
  cipher: "chacha20-ietf-poly1305"
  password: "9tqhMdIrTkgQ46PvhyAtMH"
- name: "🇸🇦_SA_沙特阿拉伯"
  type: "ss"
  server: "77.110.110.117"
  port: 443
  cipher: "chacha20-ietf-poly1305"
  password: "9JeYy8SkViXuSHVs9GFeSe"
- name: "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  type: "vmess"
  server: "77.221.143.225"
  port: 20086
  uuid: "149b4663-aece-486a-b92c-392c41727ac1"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇺🇸_US_美国_9"
  type: "vmess"
  server: "173.208.51.193"
  port: 20086
  uuid: "b1726eb2-271b-4cb6-bae8-37647e78b776"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇰🇷_KR_韩国->🇺🇸_US_美国"
  type: "vmess"
  server: "154.223.19.231"
  port: 20086
  uuid: "bfb323d3-239e-4e1b-bfa8-13f68385931e"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/"
  alterId: 0
- name: "🇺🇸_US_美国_10"
  type: "ss"
  server: "38.54.57.90"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  type: "vmess"
  server: "fastcup.net"
  port: 80
  sni: ""
  uuid: "76414574-71e0-4706-89cc-c5b09c13445d"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/profile/telegram@ssrsub"
    headers:
      host: "cdn-node-oss-99.paofu.de"
  alterId: 0
- name: "🇩🇪_DE_德国_3"
  type: "ss"
  server: "45.87.175.58"
  port: 8080
  cipher: "chacha20-ietf-poly1305"
  password: "oZIoA69Q8yhcQV8ka3Pa3A"
- name: "🇷🇺_RU_俄罗斯_1"
  type: "ss"
  server: "95.163.176.37"
  port: 8506
  cipher: "chacha20-ietf-poly1305"
  password: "eUh4lSpi7nOYj0vSrqLUh0"
- name: "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  type: "vmess"
  server: "185.193.29.88"
  port: 8880
  uuid: "cc0926df-54a8-3df7-934c-fd3ead64f6aa"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/dabai&Telegram🇨🇳 @WangCai2 /?ed=2560"
    headers:
      host: "TG.WangCai2.s2.cn-db.top"
  alterId: 0
- name: "🇬🇧_GB_英国->🇺🇸_US_美国"
  type: "ss"
  server: "85.210.120.237"
  port: 443
  cipher: "chacha20-ietf-poly1305"
  password: "Bog0ELmMM9DSxDdQ"
- name: "🇨🇳_CN_中国->🇺🇸_US_美国_1"
  type: "vmess"
  server: "154.197.108.88"
  port: 8880
  uuid: "cc0926df-54a8-3df7-934c-fd3ead64f6aa"
  cipher: "auto"
  network: "ws"
  ws-opts:
    path: "/dabai&Telegram🇨🇳 @WangCai2 /?ed=2560"
    headers:
      host: "TG.WangCai2.s2.cn-db.top"
  alterId: 0
proxy-groups:
- name: "🚀 节点选择"
  type: "select"
  proxies:
  - "♻️ 自动选择"
  - "DIRECT"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "♻️ 自动选择"
  type: "url-test"
  url: "http://www.gstatic.com/generate_204"
  interval: 300
  tolerance: 50
  proxies:
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "🌍 国外媒体"
  type: "select"
  proxies:
  - "🚀 节点选择"
  - "♻️ 自动选择"
  - "🎯 全球直连"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "📲 电报信息"
  type: "select"
  proxies:
  - "🚀 节点选择"
  - "🎯 全球直连"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "Ⓜ️ 微软服务"
  type: "select"
  proxies:
  - "🎯 全球直连"
  - "🚀 节点选择"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "🍎 苹果服务"
  type: "select"
  proxies:
  - "🚀 节点选择"
  - "🎯 全球直连"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
- name: "🎯 全球直连"
  type: "select"
  proxies:
  - "DIRECT"
  - "🚀 节点选择"
  - "♻️ 自动选择"
- name: "🛑 全球拦截"
  type: "select"
  proxies:
  - "REJECT"
  - "DIRECT"
- name: "🍃 应用净化"
  type: "select"
  proxies:
  - "REJECT"
  - "DIRECT"
- name: "🐟 漏网之鱼"
  type: "select"
  proxies:
  - "🚀 节点选择"
  - "🎯 全球直连"
  - "♻️ 自动选择"
  - "🇳🇱_NL_荷兰"
  - "🇨🇦_CA_加拿大->🇺🇸_US_美国"
  - "🇸🇰_SK_斯洛伐克->🇨🇳_CN_中国"
  - "🇷🇺_RU_俄罗斯"
  - "🇺🇸_US_美国"
  - "🇮🇳_IN_印度->🇫🇷_FR_法国"
  - "🇺🇸_US_美国_1"
  - "🇺🇸_US_美国_2"
  - "🇩🇪_DE_德国"
  - "🇺🇸_US_美国_3"
  - "🇩🇪_DE_德国_1"
  - "🇬🇧_GB_英国"
  - "🇺🇸_US_美国_4"
  - "🇺🇸_US_美国_5"
  - "🇩🇪_DE_德国_2"
  - "🇺🇸_US_美国_6"
  - "🇨🇳_CN_中国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_8"
  - "🇺🇦_UA_乌克兰"
  - "🇸🇦_SA_沙特阿拉伯"
  - "🇷🇺_RU_俄罗斯->🏳️_unKnow_未知"
  - "🇺🇸_US_美国_9"
  - "🇰🇷_KR_韩国->🇺🇸_US_美国"
  - "🇺🇸_US_美国_10"
  - "🇩🇰_DK_丹麦->🇺🇸_US_美国"
  - "🇩🇪_DE_德国_3"
  - "🇷🇺_RU_俄罗斯_1"
  - "🇳🇱_NL_荷兰->🇺🇸_US_美国"
  - "🇬🇧_GB_英国->🇺🇸_US_美国"
  - "🇨🇳_CN_中国->🇺🇸_US_美国_1"
rule-providers:
  Apple:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
    format: "text"
    interval: 3600
    path: "./Clash/Apple.list"
  Telegram:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
    format: "text"
    interval: 3600
    path: "./Clash/Telegram.list"
  ProxyLite:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list"
    format: "text"
    interval: 3600
    path: "./Clash/ProxyLite.list"
  ChinaDomain:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
    format: "text"
    interval: 3600
    path: "./Clash/ChinaDomain.list"
  ChinaCompanyIp:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
    format: "text"
    interval: 3600
    path: "./Clash/ChinaCompanyIp.list"
  ProxyMedia:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
    format: "text"
    interval: 3600
    path: "./Clash/ProxyMedia.list"
  LocalAreaNetwork:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
    format: "text"
    interval: 3600
    path: "./Clash/LocalAreaNetwork.list"
  Microsoft:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
    format: "text"
    interval: 3600
    path: "./Clash/Microsoft.list"
  GoogleCN:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
    format: "text"
    interval: 3600
    path: "./Clash/GoogleCN.list"
  BanAD:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
    format: "text"
    interval: 3600
    path: "./Clash/BanAD.list"
  BanProgramAD:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
    format: "text"
    interval: 3600
    path: "./Clash/BanProgramAD.list"
  SteamCN:
    type: "http"
    behavior: "classical"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
    format: "text"
    interval: 3600
    path: "./Clash/SteamCN.list"
rules:
- "RULE-SET,LocalAreaNetwork,🎯 全球直连"
- "RULE-SET,BanAD,🛑 全球拦截"
- "RULE-SET,BanProgramAD,🍃 应用净化"
- "RULE-SET,GoogleCN,🎯 全球直连"
- "RULE-SET,SteamCN,🎯 全球直连"
- "RULE-SET,Microsoft,Ⓜ️ 微软服务"
- "RULE-SET,Apple,🍎 苹果服务"
- "RULE-SET,ProxyMedia,🌍 国外媒体"
- "RULE-SET,Telegram,📲 电报信息"
- "RULE-SET,ProxyLite,🚀 节点选择"
- "RULE-SET,ChinaDomain,🎯 全球直连"
- "RULE-SET,ChinaCompanyIp,🎯 全球直连"
- "GEOIP,CN,🎯 全球直连"
- "MATCH,🐟 漏网之鱼"
