name: Update Clash Configs

on:
  schedule:
    - cron: '0 16,22 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install beautifulsoup4 requests
        
    - name: Run scraper
      run: python clash_scraper.py
      
    - name: Commit and push changes
      env:
        REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Clash configs [auto]"
        git remote set-url origin $REPO_URL
        git push
